# Dockerfile.alerts_ui
FROM node:20

WORKDIR /app

# Copy package.json & package-lock.json first
COPY alerts_ui/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY alerts_ui/ .

# Expose port
EXPOSE 3000

ENV HOST 0.0.0.0
ENV PORT 3000

# Start Vite dev server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]