version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - kafka

  sales_consumer:
    build: ./sales_consumer
    container_name: sales_consumer
    depends_on:
      - kafka
      - redis

  alert_consumer:
    build: ./alert_consumer
    container_name: alert_consumer
    depends_on:
      - kafka
      - redis

  alert_service:
    build: ./alert_service
    container_name: alert_service
    ports:
      - "4000:4000"
    depends_on:
      - redis

  alerts_ui:
    build: ./alerts_ui
    container_name: alerts_ui
    ports:
      - "3000:3000"
    depends_on:
      - alert_service
