# Use Node.js 20
FROM node:20

WORKDIR /app

# Copy only package.json and package-lock.json first to leverage caching
COPY alerts_ui/package*.json ./

RUN npm install

# Copy the rest of the React app
COPY alerts_ui/ .

# Expose port
EXPOSE 3000

# Start Vite dev server
CMD ["npm", "run", "dev", "--", "--host"]
