FROM python:3.11-slim

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir fastapi uvicorn kafka-python redis

CMD ["python", "alert_service.py"]
# For producer or sales_consumer, override CMD in docker-compose.yml