apiVersion: example.com/v1
kind: EtherealPod
metadata:
  name: example-ep
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
      restartPolicy: Always